name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  publish_github:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - uses: gradle/actions/setup-gradle@v4

      - name: Publish to GitHub Packages
        run: ./gradlew :library:publishReleasePublicationToGitHubPackagesRepository
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}

  publish_ossrh:
    name: Publish to OSSRH (Central Portal)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - uses: gradle/actions/setup-gradle@v4

      - name: Build Central Bundle
        run: ./gradlew :library:publishReleasePublicationToCentralPortalBundleRepository
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}

      - name: Zip bundle
        run: |
          cd library/build/central-bundle
          zip -r ../central-bundle.zip .

      - name: Upload to Sonatype Central Portal
        run: |
          curl --request POST \
            --url "https://central.sonatype.com/api/v1/publisher/upload?publishingType=AUTOMATIC" \
            --user "${{ secrets.OSSRH_TOKEN_KEY }}:${{ secrets.OSSRH_TOKEN_PASSWORD }}" \
            --form "bundle=@library/build/central-bundle.zip"